####### Lent try Adam to approach 0.933 ...
###### Lenet-accelerate-1, panda14-2
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname lenet -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-15.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname lenet -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-16.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_lasso.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 7 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-61.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_maxnorm.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 8 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-70.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.1 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-114.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.2 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-115.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.3 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-116.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-117.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.7 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-118.log
CUDA_VISIBLE_DEVICES=2 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.9 | tee -a /hdd2/zhaojing/res-regularization/20-8-5/20-8-5-first-run/20-8-5-first-run-accelerate-119.log
