###### MLP-MNIST-1, panda1-1
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname mlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-1.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname mlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-2.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname mlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-3.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname mlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-4.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001_tune_lasso_864.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname regmlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 7 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-5.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001_tune_maxnorm_234.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname regmlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 8 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-6.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname dropoutregmlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 9 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 --dropout 0.1 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-7.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname dropoutregmlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 9 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 --dropout 0.2 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-8.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_wd0001.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname dropoutregmlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 9 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 --dropout 0.3 | tee -a /hdd2/zhaojing/res-regularization/20-8-15/20-8-15-second-run/20-8-15-second-run-9.log
