###### Lenet
### panda15-1
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname lenet -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-125.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname lenet -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-126.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname lenet -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-127.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_lasso_86.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 7 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-128.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_lasso_86.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 7 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-129.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_lasso_86.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 7 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-130.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_maxnorm_34.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 8 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-131.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_maxnorm_34.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 8 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-132.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_maxnorm_34.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 8 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-133.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-134.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-135.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0.py -modelname dropoutreglenet -firstepochs 0 -considerlabelnum 1 -regmethod 9 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-136.log
### 18 (16 hours: 48)
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_corr_reg_lenet_e8.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 6 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-137.log
CUDA_VISIBLE_DEVICES=1 /hdd1/zhaojing/anaconda3-cuda-10/bin/python lenet_main_NLL_GPU_Adam_wd0_tune_corr_reg_lenet_e8.py -modelname reglenet -firstepochs 0 -considerlabelnum 1 -regmethod 6 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-average/8-28-fourth-run-average-138.log
############################################ 20-8-28-end !!!!!!!!!!!!!! ##############################################