### run again for vis of autoencoder ... (one layer is worse than baseline ...)
### panda1-1
### autoencoder
CUDA_VISIBLE_DEVICES=1 python autoencoder_MNIST_main_SGD_lr10_wd000001_autoencoder_tune_corr_reg_vis.py -modelname regautoenc -firstepochs 0 -considerlabelnum 1 -regmethod 6 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-1.log
CUDA_VISIBLE_DEVICES=1 python autoencoder_MNIST_main_SGD_lr10_wd000001_autoencoder_vis.py -modelname autoenc -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-2.log
### run again for corr_mean_var for autoencoder (now print first 10 epochs)
### autoencoder
CUDA_VISIBLE_DEVICES=1 python autoencoder_MNIST_main_SGD_lr10_wd000001_autoencoder_corr_reg_corr_mean_var.py -modelname regautoenc -firstepochs 0 -considerlabelnum 1 -regmethod 6 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-3.log
CUDA_VISIBLE_DEVICES=1 python autoencoder_MNIST_main_SGD_lr10_wd000001_autoencoder_wd_corr_mean_var.py -modelname autoenc -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-4.log
#### corr_mean_var (wd=0)
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_mlp_mnist_wd0_corr_mean_var.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname mlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 200 -gpuid 0 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-5.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_mlp_mimic_iii_wd0_corr_mean_var.py -traindatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_x_seq_sparse.npz -trainlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_y_seq.csv -testdatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_x_seq_sparse.npz -testlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_y_seq.csv -seqnum 9 -modelname mlp -blocks 1 -lr 0.3 -batchsize 100 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 500 -gpuid 0 --batch_first | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-6.log
CUDA_VISIBLE_DEVICES=1 python mlp_residual_hook_resreg_real_mnist_mlp_movie_wd0_corr_mean_var.py -traindatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_x_seq_word2vec200_window50_mlp.csv -trainlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_y_seq_word2vec200_window50_mlp.csv -testdatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_x_seq_word2vec200_window50_mlp.csv -testlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_y_seq_word2vec200_window50_mlp.csv -seqnum 25 -modelname mlp -blocks 1 -lr 0.01 -batchsize 100 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 500 -gpuid 0 --batch_first | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-7.log
CUDA_VISIBLE_DEVICES=1 python train_lstm_main_hook_resreg_real_wlm_lstm_mimic_iii_wd0_corr_mean_var.py -traindatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_x_seq_sparse.npz -trainlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_y_seq.csv -testdatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_x_seq_sparse.npz -testlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_y_seq.csv -seqnum 9 -modelname lstm -blocks 1 -lr 1.0 -batchsize 100 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 500 -gpuid 0 --batch_first --nhid 128 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-8.log
CUDA_VISIBLE_DEVICES=1 python train_lstm_main_hook_resreg_real_wlm_lstm_movie_wd0_corr_mean_var.py -traindatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_x_seq_word2vec200_window50.csv -trainlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_y_seq_word2vec200_window50.csv -testdatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_x_seq_word2vec200_window50.csv -testlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_y_seq_word2vec200_window50.csv -seqnum 25 -modelname lstm -blocks 1 -lr 0.3 -batchsize 100 -regmethod 100 -firstepochs 0 -considerlabelnum 1 -maxepoch 500 -gpuid 0 --batch_first --nhid 128 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-9.log
CUDA_VISIBLE_DEVICES=1 python autoencoder_MNIST_main_SGD_lr10_wd000001_autoencoder_wd0_corr_mean_var.py -modelname autoenc -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-10.log
CUDA_VISIBLE_DEVICES=1 python lenet_main_NLL_GPU_Adam_wd0_lenet_wd0_corr_mean_var.py -modelname lenet -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-11.log
CUDA_VISIBLE_DEVICES=1 python vgg_main_lr05_wd0005_vgg_wd0_corr_mean_var.py -modelname vgg16_bn -firstepochs 0 -considerlabelnum 1 -regmethod 100 --dropout 0.5 --save-dir=save_vgg16 | tee -a /hdd2/zhaojing/res-regularization/20-8-28/20-8-28-fourth-run-visualization/20-8-28-fourth-run-visualization-12.log
############################################ 20-8-28-end !!!!!!!!!!!!!! ##############################################