# MLP--MNIST--hidden hard-coded 100
# ncra2 
CUDA_VISIBLE_DEVICES=2 python mlp_residual_hook_resreg_real_mnist_tune_hyperparam.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname mlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 5 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 | tee -a 19-4-20-test-tune-hyper-1.log
CUDA_VISIBLE_DEVICES=2 python mlp_residual_hook_resreg_real_mnist_tune_hyperparam.py -traindatadir MNIST -trainlabeldir MNIST -testdatadir MNIST -testlabeldir MNIST -seqnum 1 -modelname regmlp -blocks 1 -lr 0.01 -batchsize 65 -regmethod 5 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 | tee -a 19-4-20-test-tune-hyper-2.log
# MLP-MIMIC-III--hidden hard-coded 128
# ncra2 
CUDA_VISIBLE_DEVICES=2 python mlp_residual_hook_resreg_real_mnist_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_x_seq_sparse.npz -trainlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_y_seq.csv -testdatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_x_seq_sparse.npz -testlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_y_seq.csv -seqnum 9 -modelname mlp -blocks 1 -lr 0.3 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first | tee -a 19-4-20-test-tune-hyper-3.log
CUDA_VISIBLE_DEVICES=2 python mlp_residual_hook_resreg_real_mnist_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_x_seq_sparse.npz -trainlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_y_seq.csv -testdatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_x_seq_sparse.npz -testlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_y_seq.csv -seqnum 9 -modelname regmlp -blocks 1 -lr 0.3 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first | tee -a 19-4-20-test-tune-hyper-4.log
# MLP-Movie-Review--hidden hard-coded 128
# ncra2 
CUDA_VISIBLE_DEVICES=2 python mlp_residual_hook_resreg_real_mnist_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_x_seq_word2vec200_window50_mlp.csv -trainlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_y_seq_word2vec200_window50_mlp.csv -testdatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_x_seq_word2vec200_window50_mlp.csv -testlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_y_seq_word2vec200_window50_mlp.csv -seqnum 25 -modelname mlp -blocks 1 -lr 0.01 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first | tee -a 19-4-20-test-tune-hyper-5.log
CUDA_VISIBLE_DEVICES=2 python mlp_residual_hook_resreg_real_mnist_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_x_seq_word2vec200_window50_mlp.csv -trainlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_y_seq_word2vec200_window50_mlp.csv -testdatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_x_seq_word2vec200_window50_mlp.csv -testlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_y_seq_word2vec200_window50_mlp.csv -seqnum 25 -modelname regmlp -blocks 1 -lr 0.01 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first | tee -a 19-4-20-test-tune-hyper-6.log
###########################################################
# LSTM-MIMIC-III
# ncra2 
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_x_seq_sparse.npz -trainlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_y_seq.csv -testdatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_x_seq_sparse.npz -testlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_y_seq.csv -seqnum 9 -modelname lstm -blocks 1 -lr 1.0 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first --nhid 128 | tee -a 19-4-20-test-tune-hyper-7.log
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_x_seq_sparse.npz -trainlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_train_y_seq.csv -testdatadir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_x_seq_sparse.npz -testlabeldir /hdd1/zhaojing/res-regularization/MIMIC-III-dataset/formal_test_y_seq.csv -seqnum 9 -modelname reglstm -blocks 1 -lr 1.0 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first --nhid 128 | tee -a 19-4-20-test-tune-hyper-8.log
# LSTM-Moview-Review
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_x_seq_word2vec200_window50.csv -trainlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_y_seq_word2vec200_window50.csv -testdatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_x_seq_word2vec200_window50.csv -testlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_y_seq_word2vec200_window50.csv -seqnum 25 -modelname lstm -blocks 1 -lr 0.3 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first --nhid 128 | tee -a 19-4-20-test-tune-hyper-9.log
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_x_seq_word2vec200_window50.csv -trainlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_train_y_seq_word2vec200_window50.csv -testdatadir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_x_seq_word2vec200_window50.csv -testlabeldir /hdd1/zhaojing/res-regularization/Movie_Review/correct_movie_review_test_y_seq_word2vec200_window50.csv -seqnum 25 -modelname reglstm -blocks 1 -lr 0.3 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --batch_first --nhid 128 | tee -a 19-4-20-test-tune-hyper-10.log
# LSTM-WLM
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir ./data/wikitext-2 -trainlabeldir ./data/wikitext-2 -testdatadir ./data/wikitext-2 -testlabeldir ./data/wikitext-2 -seqnum 35 -modelname lstm -blocks 1 -lr 20.0 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --emsize 200 --nhid 200 --clip 0.25 --seed 1111 | tee -a 19-4-20-test-tune-hyper-11.log
# blocks=2, clip=0.2557
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir ./data/wikitext-2 -trainlabeldir ./data/wikitext-2 -testdatadir ./data/wikitext-2 -testlabeldir ./data/wikitext-2 -seqnum 35 -modelname lstm -blocks 2 -lr 20.0 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --emsize 200 --nhid 200 --clip 0.2557 --seed 1111 | tee -a 19-4-20-test-tune-hyper-12.log
# blocks=3, clip=0.2615
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir ./data/wikitext-2 -trainlabeldir ./data/wikitext-2 -testdatadir ./data/wikitext-2 -testlabeldir ./data/wikitext-2 -seqnum 35 -modelname lstm -blocks 3 -lr 20.0 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --emsize 200 --nhid 200 --clip 0.2615 --seed 1111 | tee -a 19-4-20-test-tune-hyper-13.log
CUDA_VISIBLE_DEVICES=2 python train_lstm_main_hook_resreg_real_wlm_tune_hyperparam.py -traindatadir ./data/wikitext-2 -trainlabeldir ./data/wikitext-2 -testdatadir ./data/wikitext-2 -testlabeldir ./data/wikitext-2 -seqnum 35 -modelname reglstm -blocks 1 -lr 20.0 -batchsize 100 -regmethod 6 -firstepochs 0 -considerlabelnum 1 -maxepoch 3 -gpuid 0 --emsize 200 --nhid 200 --clip 0.25 --seed 1111 | tee -a 19-4-20-test-tune-hyper-14.log